CREATE TABLE [Books] (
	Id int NOT NULL IDENTITY,
	Name nvarchar(100) NOT NULL,
	GenreId int NOT NULL,
	PublisherId int NOT NULL,
	Year int NOT NULL,
	Pages int NOT NULL,
	Price money NOT NULL,
  CONSTRAINT [PK_BOOKS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Authors] (
	Id int NOT NULL IDENTITY,
	Name nvarchar(100) NOT NULL,
  CONSTRAINT [PK_AUTHORS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [BooksAuthors] (
	Id int NOT NULL IDENTITY,
	BookId int NOT NULL,
	AuthorId int NOT NULL,
  CONSTRAINT [PK_BOOKSAUTHORS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Genres] (
	Id int NOT NULL IDENTITY,
	Name nvarchar(100) NOT NULL,
  CONSTRAINT [PK_GENRES] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Publishers] (
	Id int NOT NULL IDENTITY,
	Name nvarchar(100) NOT NULL,
  CONSTRAINT [PK_PUBLISHERS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Managers] (
	Id int NOT NULL IDENTITY,
	Name nvarchar(100) NOT NULL,
	Contact nvarchar(100) NOT NULL,
  CONSTRAINT [PK_MANAGERS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Readers] (
	Id int NOT NULL IDENTITY,
	Name nvarchar(100) NOT NULL,
	Contact nvarchar(100) NOT NULL,
  CONSTRAINT [PK_READERS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Journal] (
	Id int NOT NULL IDENTITY,
	BookId int NOT NULL,
	ManagerId int NOT NULL,
	ReaderId int NOT NULL,
	IssueDate date NOT NULL,
	ReturnDate date,
  CONSTRAINT [PK_JOURNAL] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
ALTER TABLE [Books] WITH CHECK ADD CONSTRAINT [Books_fk0] FOREIGN KEY ([GenreId]) REFERENCES [Genres]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Books] CHECK CONSTRAINT [Books_fk0]
GO
ALTER TABLE [Books] WITH CHECK ADD CONSTRAINT [Books_fk1] FOREIGN KEY ([PublisherId]) REFERENCES [Publishers]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Books] CHECK CONSTRAINT [Books_fk1]
GO


ALTER TABLE [BooksAuthors] WITH CHECK ADD CONSTRAINT [BooksAuthors_fk0] FOREIGN KEY ([BookId]) REFERENCES [Books]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [BooksAuthors] CHECK CONSTRAINT [BooksAuthors_fk0]
GO
ALTER TABLE [BooksAuthors] WITH CHECK ADD CONSTRAINT [BooksAuthors_fk1] FOREIGN KEY ([AuthorId]) REFERENCES [Authors]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [BooksAuthors] CHECK CONSTRAINT [BooksAuthors_fk1]
GO


ALTER TABLE [Journal] WITH CHECK ADD CONSTRAINT [Journal_fk0] FOREIGN KEY ([BookId]) REFERENCES [Books]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Journal] CHECK CONSTRAINT [Journal_fk0]
GO
ALTER TABLE [Journal] WITH CHECK ADD CONSTRAINT [Journal_fk1] FOREIGN KEY ([ManagerId]) REFERENCES [Managers]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Journal] CHECK CONSTRAINT [Journal_fk1]
GO
ALTER TABLE [Journal] WITH CHECK ADD CONSTRAINT [Journal_fk2] FOREIGN KEY ([ReaderId]) REFERENCES [Readers]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Journal] CHECK CONSTRAINT [Journal_fk2]
GO

